
import java.awt.Color;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aleha
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    public MenuPrincipal() {
        setExtendedState(MAXIMIZED_BOTH);
        setIcon();
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Teste = new javax.swing.JPopupMenu();
        CriarMateria = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        nome4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        nome5 = new javax.swing.JMenuItem();
        PainelMenu = new javax.swing.JPanel();
        botaoMaterias = new javax.swing.JButton();
        PainelMenu2 = new javax.swing.JPanel();
        botaoSair = new javax.swing.JButton();

        Teste.setBackground(new java.awt.Color(255, 255, 255));
        Teste.setBorderPainted(false);
        Teste.setPreferredSize(new java.awt.Dimension(148, 92));
        Teste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TesteMouseExited(evt);
            }
        });

        CriarMateria.setText("Criar nova matéria");
        Teste.add(CriarMateria);
        Teste.add(jSeparator1);

        nome4.setText("Português");
        nome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome4ActionPerformed(evt);
            }
        });
        Teste.add(nome4);
        Teste.add(jSeparator2);

        nome5.setText("Teste");
        Teste.add(nome5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusCycleRoot(false);
        setFocusableWindowState(false);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        PainelMenu.setBackground(new java.awt.Color(102, 102, 255));

        botaoMaterias.setBackground(new java.awt.Color(214, 220, 244));
        botaoMaterias.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        botaoMaterias.setText("Matérias");
        botaoMaterias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botaoMaterias.setBorderPainted(false);
        botaoMaterias.setContentAreaFilled(false);
        botaoMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMateriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMateriasMouseExited(evt);
            }
        });
        botaoMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMateriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMenuLayout = new javax.swing.GroupLayout(PainelMenu);
        PainelMenu.setLayout(PainelMenuLayout);
        PainelMenuLayout.setHorizontalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1148, Short.MAX_VALUE))
        );
        PainelMenuLayout.setVerticalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        PainelMenu2.setBackground(new java.awt.Color(102, 102, 255));

        botaoSair.setBackground(new java.awt.Color(214, 220, 244));
        botaoSair.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botaoSair.setBorderPainted(false);
        botaoSair.setContentAreaFilled(false);
        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSairMouseExited(evt);
            }
        });
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMenu2Layout = new javax.swing.GroupLayout(PainelMenu2);
        PainelMenu2.setLayout(PainelMenu2Layout);
        PainelMenu2Layout.setHorizontalGroup(
            PainelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMenu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelMenu2Layout.setVerticalGroup(
            PainelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMenu2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(PainelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(767, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMateriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMateriasMouseEntered
        Teste.show(this, botaoMaterias.getX()+32 , PainelMenu.getY()+64);
        botaoMaterias.setBackground(Color.BLUE);
        botaoMaterias.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMateriasMouseEntered

    private void nome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome4ActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_nome4ActionPerformed

    private void TesteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TesteMouseExited
        botaoMaterias.setBackground(Color.WHITE);
        botaoMaterias.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_TesteMouseExited

    private void botaoMateriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMateriasMouseExited
        botaoMaterias.setBackground(Color.WHITE);
        botaoMaterias.setForeground(Color.BLACK);    
    // TODO add your handling code here:
        
    }//GEN-LAST:event_botaoMateriasMouseExited

    private void botaoMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMateriasActionPerformed

    private void botaoSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseEntered
        botaoSair.setForeground(Color.WHITE);
    // TODO add your handling code here:
        
    }//GEN-LAST:event_botaoSairMouseEntered

    private void botaoSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseExited
         botaoSair.setForeground(Color.BLACK);
// TODO add your handling code here:
    }//GEN-LAST:event_botaoSairMouseExited

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CriarMateria;
    private javax.swing.JPanel PainelMenu;
    private javax.swing.JPanel PainelMenu1;
    private javax.swing.JPanel PainelMenu2;
    private javax.swing.JPopupMenu Teste;
    private javax.swing.JButton botaoMaterias;
    private javax.swing.JButton botaoMaterias1;
    private javax.swing.JButton botaoSair;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem nome4;
    private javax.swing.JMenuItem nome5;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
  //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("favicon.png")));
    }
}
